### PR TITLE
WIP: major rewrite

### LINKED ISSUE #6: canInteract
Using the can interact function removes the option visually however you can still scroll and click the option anyway

### PR DESCRIPTION
**Pull request by FjamZoo**
Changelog
- Changed IDs to be strings that users can implement
- Added table.remove instead of table[index] = nil
- Redid canInteract to filter out options in the API
- Lowered the default 500ms api loop to 250 (script runs at 0.04ms on 250 and 0.03ms on 500 while looking at interactions)
- optimized the disabled loop
- Localized the Playerstate to make it more performant
- Should fix https://github.com/darktrovx/interact/issues/6
- Added a function that verifies contents inside of interactions and entity interactions
- Added a convar for how often the main thread should run
- Cleaned up some unused variables such as settings.textures
- Added framework intergration as suggested here: https://github.com/darktrovx/interact/issues/4
- Splitting up entities to its own submodule to avoid redudency
- Added a defaults submodule which can be disabled via convars
- added global vehicle interaction
- depreciated AddBoneInteraciton (not needed anymore use AddEntityInteraction or AddLocalEntityInteraction)
- depreciated RemoveInteractionByEntity which will be replaced by other functions

This is extremely WIP and majority of the code has only SLIGHTLY been tested

### CODE REVIEW

**Comment by FjamZoo** [comment]
Scope of the PR has shifted slightly from doing general cleanups and improvements to trying to handle our internal data a lot better.

Currently in the main branch entities are redundant and uses a lot of resources by running multiple different threads every 250ms.

Introducing a new module that will handle internal entities should help it be slightly more performant without losing much ram usage.

**Comment by FjamZoo** [comment]
If anyone wants to test this please do so.

Most things apart from hashes should work, and everything is 100% backwards compatible as of now.

**Comment by Knvctedd** [comment]
i am getting this error now 
image

**Comment by FjamZoo** [comment]
> i am getting this error now image

Is there any particular interaction options this happens?

I'm running just default with a few test ones and they do seem to work just fine

**Comment by jnccloud** [comment]
@FjamZoo this is Castar, Ive been testing this but I cannot get `exports.interact:AddModelInteraction` to work. Readme says it accepts a table, doesn't look that way in code. So I passed a single object and it didn't display anything. Using `prop_dumpster_01a` as an example, with the dumpsters behind legion bank.

**Comment by FjamZoo** [comment]
> @FjamZoo this is Castar, Ive been testing this but I cannot get `exports.interact:AddModelInteraction` to work. Readme says it accepts a table, doesn't look that way in code. So I passed a single object and it didn't display anything. Using `prop_dumpster_01a` as an example, with the dumpsters behind legion bank.

AddInteractModel is currently not implemented, I never got to work on it yesterday which was my primary focus, but got sidetracked with global vehicles and refactor etc.

This will hopefully be added today

**Pull request merged**
